### ISSUE TITLE
Support for Gatsby V4

### ISSUE THREAD

**Issue by rafcontreras** [universse/gatsby-plugin-workerize-loader#11]
I've been using Gatsby V4 with v2 of this plugin with zero issues. Could you add version 4 to the peerDependencies?

**Comment by phuoccss** [comment]
Hi, thanks for the heads-up. I've just published a new version.

**Comment by 0xdagu** [comment]
I had to use this command

```
npm install --save-dev gatsby-plugin-workerize-loader --legacy-peer-deps
```
