### ISSUE TITLE
Gatsby Plugin Typescript Integration

### ISSUE THREAD

**Issue by reggie3** [universse/gatsby-plugin-workerize-loader#4]
Does this plugin work alongside `gatsby-plugin-typescript`?  I'm attempting to add a webworker to an existing working TypeScript gatsby project, and I'm not currently seeing an additional thread created even though the code that should be in the webworker is running.

I just wanted to know if this plugin works with the Typescript plugin before I did more troubleshooting.

**Comment by phuoccss** [comment]
Hi there. The current version does not detect `.ts` extension. You can upgrade to version `1.3.0` and see how it goes. I tested locally and it seems to work.

**Comment by reggie3** [comment]
Thanks. Using 1.3.0 solved my problem
